# Generated by Django 3.2.5 on 2021-07-13 22:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=150, verbose_name='Service Provider Name')),
                ('email', models.EmailField(max_length=150, verbose_name='Service Provider Email')),
                ('phone_number', models.CharField(max_length=17)),
                ('language', models.CharField(default='en-us', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=150, verbose_name='Service Area Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_area', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas_of', to='geofence.serviceprovider')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
